In [1]:
import numpy as np 
print(np.__version__)

1.24.2


*SOME BASICS*


In [2]:
arr = np.array ([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


*DIMENSIONS*

In [3]:
arr_2d = np.array ([[1, 2, 3], [4, 5, 6]])

print(arr_2d)

arr_3d = np.array ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

arr_5d = np.array([1, 2, 3, 4], ndmin=5)
print(arr_5d)


[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[[[1 2 3 4]]]]]


In [4]:
print(arr.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)
print(arr_5d.ndim)

1
2
3
5


ACCESSING AND SLICING

In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0,2])

for i in arr:
    for j in i:
        print(j)

3
1
2
3
4
5
6
7
8
9
10


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:3])
print(arr[-5:-1])
print(arr[0:6:2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[1 2 3]
[3 4 5 6]
[1 3 5]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


DATA TYPES


In [7]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U6
int32
[b'1' b'2' b'3' b'4']
|S1


In [8]:
#Converting the data type

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i') #i = integer
# you can also use: newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
# change in original does not affect copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
# change in original does affect view

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

#change in view does not affect original


[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


SHAPE

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr_3d = np.array ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr.shape)
print(arr_3d.shape)
print(arr_5d.shape)


(2, 4)
(2, 2, 3)
(1, 1, 1, 1, 4)


In [11]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(arr)
print(newarr)

newnew_arr = newarr.reshape(-1)

print(newnew_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [18]:
# Iteration

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr)

for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

#or you can use nditer

for x in np.nditer(arr):
  print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
